# Makefile for Xtcwp library (X11 toolkit)
# DEPRECATED ON WINDOWS

ifeq ($(OS),Windows_NT)

.PHONY: all INSTALL remake clean

all INSTALL remake clean:
	@echo ========================================
	@echo DEPRECATED: Xtcwp library - X11 toolkit
	@echo ========================================
	@echo X11 components are not supported on native Windows.
	@echo Alternatives: Use WSL, VcXsrv, or Python tools.
	@echo ========================================

else
# Original Unix Makefile content would go here
include $(CWPROOT)/src/Makefile.config
# ... (Unix build rules)
endif
