# Makefile for Xmcwp library (Motif widgets)
# DEPRECATED ON WINDOWS

ifeq ($(OS),Windows_NT)

.PHONY: all INSTALL remake clean

all INSTALL remake clean:
	@echo ========================================
	@echo DEPRECATED: Xmcwp library - Motif widgets
	@echo ========================================
	@echo Motif components are not supported on Windows.
	@echo Alternatives: Use WSL or Python GUI tools.
	@echo ========================================

else
# Original Unix Makefile content would go here
include $(CWPROOT)/src/Makefile.config
# ... (Unix build rules)
endif
