# Makefile for Trielas psplot graphics
# DEPRECATED ON WINDOWS

ifeq ($(OS),Windows_NT)

.PHONY: all INSTALL remake clean

all INSTALL remake clean:
	@echo ========================================
	@echo DEPRECATED: Trielas psplot graphics
	@echo ========================================
	@echo PostScript plotting not supported on Windows.
	@echo ========================================

else
# Original Unix Makefile content would go here
include $(CWPROOT)/src/Makefile.config
# ... (Unix build rules)
endif
