# Makefile for xplot library (X11 plotting)
# DEPRECATED ON WINDOWS

ifeq ($(OS),Windows_NT)

.PHONY: all INSTALL remake clean

all INSTALL remake clean:
	@echo ========================================
	@echo DEPRECATED: xplot library - X11 plotting
	@echo ========================================
	@echo X11 plotting is not supported on native Windows.
	@echo Alternatives: Use WSL, VcXsrv, or Python tools.
	@echo ========================================

else
# Original Unix Makefile content would go here
include $(CWPROOT)/src/Makefile.config
# ... (Unix build rules)
endif
