.TH CONJTEST 1 "conjtest" "CWP/SU" "Seismic Unix Manual"
.SH NAME
conjtest \- Solving Ax=b by the conjugate gradient method The 5x4  matrix A 1
.SH SYNOPSIS
.B conjtest

[options]
.SH DESCRIPTION
Solving Ax=b by the conjugate gradient method The 5x4  matrix A 1.000000 1.000000 1.000000 0.000000
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
