.TH ELAMODEL 1 "elamodel" "CWP/SU" "Seismic Unix Manual"
.SH NAME
elamodel \- D:\src\proto\processing-su-main\bin\elamodel
.SH SYNOPSIS
.B elamodel

ERROR required parameters <fill> missing
.SH DESCRIPTION
D:\src\proto\processing-su-main\bin\elamodel.exe:
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
