.TH ELASYN 1 "elasyn" "CWP/SU" "Seismic Unix Manual"
.SH NAME
elasyn \- D:\src\proto\processing-su-main\bin\elasyn
.SH SYNOPSIS
.B elasyn

[options]
.SH DESCRIPTION
D:\src\proto\processing-su-main\bin\elasyn.exe: must specify both xg and zg
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
