.TH ELATRIUNI 1 "elatriuni" "CWP/SU" "Seismic Unix Manual"
.SH NAME
elatriuni \- D:\src\proto\processing-su-main\bin\elatriuni
.SH SYNOPSIS
.B elatriuni

[options]
.SH DESCRIPTION
D:\src\proto\processing-su-main\bin\elatriuni.exe: must specify nx!
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
