.TH FCAT 1 "fcat" "CWP/SU" "Seismic Unix Manual"
.SH NAME
fcat \- can't open --help
.SH SYNOPSIS
.B fcat

[options]
.SH DESCRIPTION
can't open --help
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
