.TH GBBEAM 1 "gbbeam" "CWP/SU" "Seismic Unix Manual"
.SH NAME
gbbeam \- D:\src\proto\processing-su-main\bin\gbbeam
.SH SYNOPSIS
.B gbbeam

[options]
.SH DESCRIPTION
D:\src\proto\processing-su-main\bin\gbbeam.exe: must specify both xg and zg
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
