.TH ISATTY 1 "isatty" "CWP/SU" "Seismic Unix Manual"
.SH NAME
isatty \- isatty: saw fildes=0, isatty? 64
.SH SYNOPSIS
.B isatty

[options]
.SH DESCRIPTION
isatty: saw fildes=0, isatty? 64
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
