.TH MAXINTS 1 "maxints" "CWP/SU" "Seismic Unix Manual"
.SH NAME
maxints \- max short =  32767 min short = -32768 max long =  2147483647
.SH SYNOPSIS
.B maxints

[options]
.SH DESCRIPTION
max short =  32767 min short = -32768 max long =  2147483647
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
