.TH SUABSHW 1 "suabshw" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suabshw \- SUABSHW - replace header key word by its absolute value suabshw <stdin >stdout key=offset
.SH SYNOPSIS
.B suabshw

\fBsuabshw\fR <stdin >stdout key=offset
.SH DESCRIPTION
SUABSHW - replace header key word by its absolute value suabshw <stdin >stdout key=offset
.SH REQUIRED PARAMETERS
none
Optional parameter:
key=offset		header key word
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
