.TH SUAI2R 1 "suai2r" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suai2r \- Acoustic Impedance to Reflectivity (Forward Modeling)
.SH SYNOPSIS
.B suai2r

\fBsuai2r\fR <stdin >sdout
.SH DESCRIPTION
Acoustic Impedance to Reflectivity (Forward Modeling)
.SH NOTES
Acoustic impedence traces in Reflectivity out
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
