.TH SUBINCSV 1 "subincsv" "CWP/SU" "Seismic Unix Manual"
.SH NAME
subincsv \- SUBINCSV - 3D Grid Resolve and output and assign traces to cdps (cells)
.SH SYNOPSIS
.B subincsv

\fBsubincsv\fR  rfile=in.csv wfile=out.csv <in.su >out.su
.SH DESCRIPTION
SUBINCSV - 3D Grid Resolve and output and assign traces to cdps (cells). subincsv  rfile=in.csv wfile=out.csv <in.su >out.su Parameter overview:
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
