.TH SUBINXXCSV 1 "subinxxcsv" "CWP/SU" "Seismic Unix Manual"
.SH NAME
subinxxcsv \- SUBINXXCSV - Expand Size and Exchange Corners of 3D Grid Definition
.SH SYNOPSIS
.B subinxxcsv

\fBsubinxxcsv\fR <stdin >stdout [parameters]
.SH DESCRIPTION
SUBINXXCSV - Expand Size and Exchange Corners of 3D Grid Definition. subinxxcsv <stdin >stdout [parameters] Parameters:
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
