.TH SUEDIT 1 "suedit" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suedit \- SUEDIT - examine segy diskfiles and edit headers suedit diskfile  (open for possible header modification if writable) suedit <diskfile  (open read only)
.SH SYNOPSIS
.B suedit

\fBsuedit\fR <diskfile  (open read only)
.SH DESCRIPTION
SUEDIT - examine segy diskfiles and edit headers suedit diskfile  (open for possible header modification if writable) suedit <diskfile  (open read only)
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
