.TH SUFARLDCSV 1 "sufarldcsv" "CWP/SU" "Seismic Unix Manual"
.SH NAME
sufarldcsv \- SUFARLDCSV - Floating Approximate Robust Local Datum From Q-files
.SH SYNOPSIS
.B sufarldcsv

direction if navrg>0,0 or nsmth>0,0
.SH DESCRIPTION
SUFARLDCSV - Floating Approximate Robust Local Datum From Q-files. The Approximate Robust Local (ARL) algorithm is intended to produce a reasonable smooth floating datum for the
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
