.TH SUFBPICKW 1 "sufbpickw" "CWP/SU" "Seismic Unix Manual"
.SH NAME
sufbpickw \- SUFBPICKW - First break auto picker sufbpickw < infile >outfile
.SH SYNOPSIS
.B sufbpickw

\fBsufbpickw\fR < infile >outfile
.SH DESCRIPTION
SUFBPICKW - First break auto picker sufbpickw < infile >outfile
.SH REQUIRED PARAMETERS
none
.SH OPTIONAL PARAMETERS
keyg=ep
window=.03	Length of forward and backward windows (s)
test=1	Output the characteristic function
This can be used for testing window size
Template
o=		offset...
t=		time pairs for defining first break search
window centre
tdv=.05	Half length of the search window
If the template is specified the maximum value of the
characteristic function is searched in the window
defined by the template only.Default is the whole trace.
The time of the pick is stored in header word unscale
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
