.TH SUFLEX2D 1 "suflex2d" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suflex2d \- SUFLEX2D - Duplicate Some Traces Into CDPs From Neighbouring CDPs
.SH SYNOPSIS
.B suflex2d

\fBsuflex2d\fR     <in.su >out.su  (other parameters)
.SH DESCRIPTION
SUFLEX2D - Duplicate Some Traces Into CDPs From Neighbouring CDPs. suflex2d     <in.su >out.su  (other parameters) This program assigns input traces of a cdp to offset bins (offset ranges).
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
