.TH SUGETQCSV 1 "sugetqcsv" "CWP/SU" "Seismic Unix Manual"
.SH NAME
sugetqcsv \- SUGETQCSV - Write Trace Header Key Values and Sample Values to a Q-file sugetqcsv [parameters]
.SH SYNOPSIS
.B sugetqcsv

[options]
.SH DESCRIPTION
SUGETQCSV - Write Trace Header Key Values and Sample Values to a Q-file sugetqcsv [parameters]. Parameters:
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
