.TH SUHILB 1 "suhilb" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suhilb \- SUHILB - Hilbert transform suhilb <stdin >sdout Note: the transform is computed in the direct (time) domain
.SH SYNOPSIS
.B suhilb

\fBsuhilb\fR <stdin >sdout
.SH DESCRIPTION
SUHILB - Hilbert transform suhilb <stdin >sdout Note: the transform is computed in the direct (time) domain
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
