.TH SUINTERPFOWLER 1 "suinterpfowler" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suinterpfowler \- SUINTERPFOWLER - interpolate output image from constant velocity panels built by SUTIFOWLER or CVS These parameters should be specified the same as in SUTIFOWLER:
.SH SYNOPSIS
.B suinterpfowler

If these parameters are specified so that nvstack>5, then the input
.SH DESCRIPTION
SUINTERPFOWLER - interpolate output image from constant velocity panels built by SUTIFOWLER or CVS These parameters should be specified the same as in SUTIFOWLER:
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
