.TH SUNSZONECSV 1 "sunszonecsv" "CWP/SU" "Seismic Unix Manual"
.SH NAME
sunszonecsv \- SUNSZONECSV - Near Surface Zone Extract and Shift sunszonecsv [parameters]
.SH SYNOPSIS
.B sunszonecsv

[options]
.SH DESCRIPTION
SUNSZONECSV - Near Surface Zone Extract and Shift sunszonecsv [parameters]. Parameters:
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
