.TH SUOLDTONEW 1 "suoldtonew" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suoldtonew \- SUOLDTONEW - convert existing su data to xdr format suoldtonew <oldsu >newsu
.SH SYNOPSIS
.B suoldtonew

\fBsuoldtonew\fR <oldsu >newsu
.SH DESCRIPTION
SUOLDTONEW - convert existing su data to xdr format suoldtonew <oldsu >newsu
.SH REQUIRED PARAMETERS
none
.SH OPTIONAL PARAMETERS
none
.SH NOTES
This program is used to convert native machine datasets to
xdr-based, system-independent format.
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
