.TH SUPACK1 1 "supack1" "CWP/SU" "Seismic Unix Manual"
.SH NAME
supack1 \- SUPACK1 - pack segy trace data into chars supack1 <segy_file >packed_file	gpow=0
.SH SYNOPSIS
.B supack1

\fBsupack1\fR <segy_file >packed_file	gpow=0.5
.SH DESCRIPTION
SUPACK1 - pack segy trace data into chars supack1 <segy_file >packed_file	gpow=0.5
.SH REQUIRED PARAMETERS
none
Optional parameter:
gpow=0.5	exponent used to compress the dynamic
range of the traces
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
