.TH SUPADMISSING 1 "supadmissing" "CWP/SU" "Seismic Unix Manual"
.SH NAME
supadmissing \- SUPADMISSING - Add Dead Traces For Missing Key Values
.SH SYNOPSIS
.B supadmissing

\fBsupadmissing\fR <stdin >stdout
.SH DESCRIPTION
SUPADMISSING - Add Dead Traces For Missing Key Values. supadmissing <stdin >stdout keyloc=cdp  Input traces must be in increasing order of this key.
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
