.TH SUPACK2 1 "supack2" "CWP/SU" "Seismic Unix Manual"
.SH NAME
supack2 \- SUPACK2 - pack segy trace data into 2 byte shorts supack2 <segy_file >packed_file	gpow=0
.SH SYNOPSIS
.B supack2

\fBsupack2\fR <segy_file >packed_file	gpow=0.5
.SH DESCRIPTION
SUPACK2 - pack segy trace data into 2 byte shorts supack2 <segy_file >packed_file	gpow=0.5
.SH REQUIRED PARAMETERS
none
Optional parameter:
gpow=0.5	exponent used to compress the dynamic
range of the traces
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
