.TH SUPGC 1 "supgc" "CWP/SU" "Seismic Unix Manual"
.SH NAME
supgc \- SUPGC   -   Programmed Gain Control--apply agc like function but the same function to all traces preserving relative amplitudes spatially
.SH SYNOPSIS
.B supgc

[options]
.SH DESCRIPTION
SUPGC   -   Programmed Gain Control--apply agc like function but the same function to all traces preserving relative amplitudes spatially.
.SH OPTIONAL PARAMETERS
ntrscan=200       number of traces to scan for gain function
lwindow=1.0       length of time window in seconds
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
