.TH SUPHIDECON 1 "suphidecon" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suphidecon \- SUPHIDECON - PHase Inversion Deconvolution suphidecon < stdin > stdout
.SH SYNOPSIS
.B suphidecon

\fBsuphidecon\fR < stdin > stdout
.SH DESCRIPTION
SUPHIDECON - PHase Inversion Deconvolution suphidecon < stdin > stdout
.SH REQUIRED PARAMETERS
none
.SH OPTIONAL PARAMETERS
... time range used for wavelet extraction:
tm=-0.1	Pre zero time (maximum phase component )
tp=+0.4	Post zero time (minimum phase component + multiples)
pad=.1	percentage padding for nt prior to cepstrum calculation
pnoise=0.001	Pre-withening (assumed noise to prevent division by zero)
.SH NOTES
The wavelet is separated from the reflectivity and noise based on
their different 'smoothness' in the pseudo cepstrum domain.
The extracted wavelet also includes multiples.
The wavelet is reconstructed in frequency domain, end removed
from the trace. (Method by Lichman and Northwood, 1996.)
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
