.TH SUPROFCSV 1 "suprofcsv" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suprofcsv \- Note: You should start by looking at the 2d cdp numbering computation that exists in the subincsv program
.SH SYNOPSIS
.B suprofcsv

[options]
.SH DESCRIPTION
Note: You should start by looking at the 2d cdp numbering computation that exists in the subincsv program. For 2d lines with consistent shot and receiver coordinates and bends of less than 10 degrees or so,
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
