.TH SUPWS 1 "supws" "CWP/SU" "Seismic Unix Manual"
.SH NAME
supws \- SUPWS - Phase stack or phase-weighted stack (PWS) of adjacent traces having the same key header word
.SH SYNOPSIS
.B supws

\fBsupws\fR <stdin >stdout [optional parameters]
.SH DESCRIPTION
SUPWS - Phase stack or phase-weighted stack (PWS) of adjacent traces having the same key header word
.SH REQUIRED PARAMETERS
none
.SH OPTIONAL PARAMETERS
key=cdp	   key header word to stack on
pwr=1.0	   raise phase stack to power pwr
dt=(from header)  time sampling intervall in seconds
sl=0.0		window length in seconds used for smoothing
of the phase stack (weights)
ps=0		0 = output is PWS, 1 = output is phase stack
verbose=0	 1 = echo additional information
.SH NOTES
Phase weighted stacking is a tool for efficient incoherent noise
reduction. An amplitude-unbiased coherency measure is designed
based on the instantaneous phase, which is used to weight the
samples of an ordinary, linear stack. The result is called the
phase-weighted stack (PWS) and is cleaned from incoherent noise.
PWS thus permits detection of weak but coherent arrivals.
The phase-stack (coherency measure) has values between 0 and 1.
If the stacking is over cdp and the PWS option is set, then the
offset header field is set to zero. Otherwise, output traces get
their headers from the first trace of each data ensemble to stack,
including the offset field. Use "sushw" afterwards, if this is
not acceptable.
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
