.TH SUR2AI 1 "sur2ai" "CWP/SU" "Seismic Unix Manual"
.SH NAME
sur2ai \- Reflectivity to Acoustic Impedance (Inversion)
.SH SYNOPSIS
.B sur2ai

\fBsur2ai\fR <stdin >sdout
.SH DESCRIPTION
Reflectivity to Acoustic Impedance (Inversion)
.SH NOTES
Reflectivity traces in acoustic impedence out
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
