.TH SURECIP 1 "surecip" "CWP/SU" "Seismic Unix Manual"
.SH NAME
surecip \- SURECIP - sum opposing offsets in prepared data (see below) surecip <stdin >stdout Sum traces with equal positive and negative offsets (i
.SH SYNOPSIS
.B surecip

\fBsurecip\fR <stdin >stdout
.SH DESCRIPTION
SURECIP - sum opposing offsets in prepared data (see below) surecip <stdin >stdout Sum traces with equal positive and negative offsets (i.e. assume
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
