.TH SUREDUCE 1 "sureduce" "CWP/SU" "Seismic Unix Manual"
.SH NAME
sureduce \- SUREDUCE - convert traces to display in reduced time sureduce <stdin >stdout rv=
.SH SYNOPSIS
.B sureduce

\fBsureduce\fR <stdin >stdout rv=
.SH DESCRIPTION
SUREDUCE - convert traces to display in reduced time sureduce <stdin >stdout rv=
.SH REQUIRED PARAMETERS
dt=tr.dt	if not set in header, dt is mandatory
.SH OPTIONAL PARAMETERS
rv=8.0		reducing velocity in km/sec
Note: Useful for plotting refraction seismic data.
To remove reduction, do:
suflip < reduceddata.su flip=3 | sureduce rv=RV > flip.su
suflip < flip.su flip=3 > unreduceddata.su
Trace header fields accessed: dt, ns, offset
Trace header fields modified: none
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
