.TH SUSHIFT 1 "sushift" "CWP/SU" "Seismic Unix Manual"
.SH NAME
sushift \- SUSHIFT - shifted/windowed traces in time sushift <stdin >stdout [tmin= ] [tmax= ] tmin=			min time to pass
.SH SYNOPSIS
.B sushift

\fBsushift\fR <stdin >stdout [tmin= ] [tmax= ]
.SH DESCRIPTION
SUSHIFT - shifted/windowed traces in time sushift <stdin >stdout [tmin= ] [tmax= ] tmin=			min time to pass
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
