.TH SUSHIFTCSV 1 "sushiftcsv" "CWP/SU" "Seismic Unix Manual"
.SH NAME
sushiftcsv \- SUSHIFTCSV - Apply Static Shifts From Nearest Q-file Records
.SH SYNOPSIS
.B sushiftcsv

[options]
.SH DESCRIPTION
SUSHIFTCSV - Apply Static Shifts From Nearest Q-file Records. sushiftcsv [parameters]. Parameters:
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
