.TH SUSMOQCSV 1 "susmoqcsv" "CWP/SU" "Seismic Unix Manual"
.SH NAME
susmoqcsv \- SUSMOQCSV - Input Q-records, alter and spatially smooth, output Q-records
.SH SYNOPSIS
.B susmoqcsv

=f,l,i start at f, increment by i, end at last value <= l.
.SH DESCRIPTION
SUSMOQCSV - Input Q-records, alter and spatially smooth, output Q-records. susmoqcsv [parameters].   (No traces in or out). Parameters:
.SH NOTES
All input values are stored in double-precision (8 byte float).
This program does not care if the values are seconds or milliseconds
or feet or metres. To this program they are all just numbers.
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
