.TH SUSPECFX 1 "suspecfx" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suspecfx \- SUSPECFX - Fourier SPECtrum (T -> F) of traces suspecfx <infile >outfile Note: To facilitate further processing, the sampling interval
.SH SYNOPSIS
.B suspecfx

SUSPECFX - Fourier SPECtrum (T -> F) of traces
.SH DESCRIPTION
SUSPECFX - Fourier SPECtrum (T -> F) of traces suspecfx <infile >outfile Note: To facilitate further processing, the sampling interval
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
