.TH SUSTACK 1 "sustack" "CWP/SU" "Seismic Unix Manual"
.SH NAME
sustack \- SUSTACK - stack adjacent traces having the same key header word
.SH SYNOPSIS
.B sustack

\fBsustack\fR <stdin >stdout [Optional parameters]
.SH DESCRIPTION
SUSTACK - stack adjacent traces having the same key header word
.SH REQUIRED PARAMETERS
none
.SH OPTIONAL PARAMETERS
key=cdp		header key word to stack on
normpow=1.0	each sample is divided by the
normpow'th number of non-zero values
stacked (normpow=0 selects no division)
repeat=0	=1 repeats the stack trace nrepeat times
nrepeat=10	repeats stack trace nrepeat times in
output file
verbose=0	verbose = 1 echos information
.SH NOTES
------
The offset field is set to zero on the output traces, unless
the user is stacking with key=offset. In that case, the value
of the offset field is left unchanged.
Sushw can be used afterwards if this is not acceptable.
For VSP users:
The stack trace appears ten times in the output file when
setting repeat=1 and nrepeat=10. Corridor stacking can be
achieved by properly muting the upgoing data with SUMUTE
before stacking.
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
