.TH SUUNPACK1 1 "suunpack1" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suunpack1 \- SUUNPACK1 - unpack segy trace data from chars to floats suunpack1 <packed_file >unpacked_file suunpack1 is the approximate inverse of supack1
.SH SYNOPSIS
.B suunpack1

\fBsuunpack1\fR <packed_file >unpacked_file
.SH DESCRIPTION
SUUNPACK1 - unpack segy trace data from chars to floats suunpack1 <packed_file >unpacked_file suunpack1 is the approximate inverse of supack1
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
