.TH SUUNPACK2 1 "suunpack2" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suunpack2 \- SUUNPACK2 - unpack segy trace data from shorts to floats suunpack2 <packed_file >unpacked_file suunpack2 is the approximate inverse of supack2
.SH SYNOPSIS
.B suunpack2

\fBsuunpack2\fR <packed_file >unpacked_file
.SH DESCRIPTION
SUUNPACK2 - unpack segy trace data from shorts to floats suunpack2 <packed_file >unpacked_file suunpack2 is the approximate inverse of supack2
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
