.TH SUVELAN_UCCS 1 "suvelan_uccs" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suvelan_uccs \- SUVELAN_UCCS - compute stacking VELocity panel for cdp gathers using UnNormalized CrossCorrelation Sum
.SH SYNOPSIS
.B suvelan_uccs

\fBsuvelan_uccs\fR <stdin >stdout [optional parameters]
.SH DESCRIPTION
SUVELAN_UCCS - compute stacking VELocity panel for cdp gathers using UnNormalized CrossCorrelation Sum
.SH OPTIONAL PARAMETERS
nx=tr.cdpt              number of traces in cdp
nv=50                   number of velocities
dv=50.0                velocity sampling interval
fv=1500.0               first velocity
smute=1.5               samples with NMO stretch exceeding smute are zeroed
dtratio=5               ratio of output to input time sampling intervals
nsmooth=dtratio*2+1     length of smoothing window
verbose=0               =1 for diagnostic print on stderr
pwr=1.0                 semblance value to the power
.SH NOTES
Unnormalized crosscorrelation sum: sum all possible crosscorrelation trace
pairs in a CMP gather for each trial velocity and zero-offset two-way
travel time inside a time window. This unnormalized coherency measure
produces large spectral amplitudes for strong reflections and small
spectral amplitudes for weaker ones. If M is the number of traces in the
CMP gather M(M-1)/2 is the total number of crosscorrelations for each trial
velocity and zero-offset two-way traveltime.
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
