.TH SUVLENGTH 1 "suvlength" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suvlength \- SUVLENGTH - Adjust variable length traces to common length suvlength <vdata >stdout
.SH SYNOPSIS
.B suvlength

\fBsuvlength\fR <vdata >stdout
.SH DESCRIPTION
SUVLENGTH - Adjust variable length traces to common length suvlength <vdata >stdout
.SH REQUIRED PARAMETERS
none
.SH OPTIONAL PARAMETERS
ns=	output number of samples (default: 1st trace ns)
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
