.TH SUXEDIT 1 "suxedit" "CWP/SU" "Seismic Unix Manual"
.SH NAME
suxedit \- SUXEDIT - examine segy diskfiles and edit headers suxedit diskfile  (open for possible header modification if writable) suxedit <diskfile  (open read only)
.SH SYNOPSIS
.B suxedit

\fBsuxedit\fR <diskfile  (open read only)
.SH DESCRIPTION
SUXEDIT - examine segy diskfiles and edit headers suxedit diskfile  (open for possible header modification if writable) suxedit <diskfile  (open read only)
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
