.TH SWAPBHED 1 "swapbhed" "CWP/SU" "Seismic Unix Manual"
.SH NAME
swapbhed \- SWAPBHED - SWAP the BYTES in a SEGY Binary tape HEaDer file swapbhed < binary_in > binary out
.SH SYNOPSIS
.B swapbhed

\fBswapbhed\fR < binary_in > binary out
.SH DESCRIPTION
SWAPBHED - SWAP the BYTES in a SEGY Binary tape HEaDer file swapbhed < binary_in > binary out
.SH OPTIONAL PARAMETERS
none
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
