.TH T 1 "t" "CWP/SU" "Seismic Unix Manual"
.SH NAME
t \- 1:26 pm  Sunday,  December 7, 2025
.SH SYNOPSIS
.B t

[options]
.SH DESCRIPTION
1:26 pm  Sunday,  December 7, 2025
.SH SEE ALSO
.BR su (1),
.BR segyread (1),
.BR segywrite (1)
.SH AUTHOR
Colorado School of Mines, Center for Wave Phenomena
.SH COPYRIGHT
Copyright (c) Colorado School of Mines
